#!/usr/bin/python3
from sys import argv

with open(argv[1]) as r:
    for line in r:
        num = int(line)
        print("{:d}=".format(num), end='')
        if num % 2 == 0:
            print("{}*2".format(num//2))
            continue
        for y in range(3, num, 2):
            if num % y == 0:
                factor = num//y
                for k in range(3, factor, 2):
                    if (factor % k == 0 or k == 0):
                        break
                print("{}*{}".format(factor, y))
                break
